import { Button, Input, Picker, Radio, RadioGroup, Text, View } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { useState } from 'react'
import { StatusBar } from '@/components/status-bar'
import { type NeuterStatus, type PetDraft, type PetSex, validateRequiredPet } from '@/domain/pet'
import { petRepository } from '@/services/pet-repository'
import { createPet } from '@/domain/pet'
import './add.scss'
const types=['狗狗','猫咪','其他']; const breeds=['柯基犬','金毛犬','中华田园犬','英短','美短','其他']; const coats=['黄色','白色','黑色','灰色','花色','其他']
export default function AddPetPage(){
 const [step,setStep]=useState(0); const [form,setForm]=useState<PetDraft>({name:'',type:'',sex:'unknown'}); const [saving,setSaving]=useState(false); const patch=<K extends keyof PetDraft>(k:K,v:PetDraft[K])=>setForm(s=>({...s,[k]:v}))
 const next=()=>{const e=validateRequiredPet(form); if(e.length) return Taro.showToast({title:e[0],icon:'none'}); setStep(1)}
 const save=async()=>{if(saving)return; setSaving(true); try{await petRepository.save(createPet(form)); await Taro.showToast({title:'添加成功',icon:'success'}); setTimeout(()=>Taro.redirectTo({url:'/features/home/index'}),500)}catch{await Taro.showToast({title:'保存失败，请检查网络后重试',icon:'none'})}finally{setSaving(false)}}
 return <View className='add page'><StatusBar/><View className='add__nav'><Text onClick={()=>step?setStep(0):Taro.navigateBack()}>‹</Text><Text className='add__title'>添加宠物</Text><Text>•••</Text></View><View className='steps section-card'><Text className={step===0?'active':''}>必填信息</Text><Text className={step===1?'active':''}>选填信息</Text><Text className={step===2?'active':''}>添加成功</Text></View>{step===0?<View className='form-card section-card'><Text className='form-heading'>必填 <Text className='required'>*</Text></Text><View className='field'><Text>昵称</Text><Input maxlength={12} value={form.name} placeholder='请输入宠物昵称' onInput={e=>patch('name',e.detail.value)}/></View><Picker mode='selector' range={types} value={Math.max(types.indexOf(form.type),0)} onChange={e=>patch('type',types[Number(e.detail.value)])}><View className='field'><Text>类型</Text><Text className={form.type?'value':'placeholder'}>{form.type||'请选择宠物类型 ›'}</Text></View></Picker><View className='field field--radio'><Text>性别</Text><RadioGroup onChange={e=>patch('sex',e.detail.value as PetSex)}><Radio value='male' checked={form.sex==='male'}>弟弟</Radio><Radio value='female' checked={form.sex==='female'}>妹妹</Radio><Radio value='unknown' checked={form.sex==='unknown'}>未知</Radio></RadioGroup></View><Button className='brand-button add__continue' onClick={next}>下一步</Button></View>:<View className='form-card section-card'><Text className='form-heading'>选填</Text><View className='field'><Text>头像</Text><Text className='placeholder'>上传宠物头像 📷</Text></View><Picker mode='date' value={form.birthday||''} onChange={e=>patch('birthday',e.detail.value)}><View className='field'><Text>生日</Text><Text className={form.birthday?'value':'placeholder'}>{form.birthday||'请选择宠物生日 ›'}</Text></View></Picker><View className='field'><Text>体重</Text><Input type='digit' value={form.weight} placeholder='请输入体重（kg）' onInput={e=>patch('weight',e.detail.value)}/></View><Picker mode='selector' range={breeds} value={Math.max(breeds.indexOf(form.breed||''),0)} onChange={e=>patch('breed',breeds[Number(e.detail.value)])}><View className='field'><Text>宠物品种</Text><Text className={form.breed?'value':'placeholder'}>{form.breed||'请选择宠物品种 ›'}</Text></View></Picker><Picker mode='selector' range={coats} value={Math.max(coats.indexOf(form.coat||''),0)} onChange={e=>patch('coat',coats[Number(e.detail.value)])}><View className='field'><Text>宠物毛色</Text><Text className={form.coat?'value':'placeholder'}>{form.coat||'请选择宠物毛色 ›'}</Text></View></Picker><View className='field field--radio'><Text>绝育状况</Text><RadioGroup onChange={e=>patch('neuter',e.detail.value as NeuterStatus)}><Radio value='yes'>已绝育</Radio><Radio value='no'>未绝育</Radio><Radio value='unknown'>未知</Radio></RadioGroup></View><Button className='brand-button add__continue' disabled={saving} loading={saving} onClick={()=>void save()}>{saving?'正在保存…':'完成添加'}</Button></View>}</View>
}
